--[[
* lqs/plugins/dragonslaying.lua — Dragonslaying content browser
*
* Auto-generated by scripts/export-dragonslaying.py
* Do not edit manually — re-run the script to update.
]]--

local imgui = require('imgui');

local ui    = nil;
local items = nil;

local content = {
    {
        section = 'Tier 1 - Drakes',
        dragons = {
            {
                name       = 'Blight Wyrm',
                zone       = 'The Eldieme Necropolis',
                lv         = 66,
                difficulty = 3,
                loot       = {
                    { id = 3304, rate = 'Common' },
                    { id = 2015, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 39102, augs = { 'Rng.Acc.+5', 'Mag.Acc.+5', 'Sneak Attack+2' } },
                    { id = 39103, augs = { 'HP+7', 'Dark Magic Skill+5', 'INT+3' } },
                },
            },
            {
                name       = 'Glacial Wyvern',
                zone       = 'Xarcabard',
                lv         = 66,
                difficulty = 3,
                description = 'In the frozen wastes of Xarcabard, where the black winter never ends and the stars hang low and cold, a creature of living ice makes its lair. The Glacial Wyvern is a contradiction: beautiful and terrible. Its scales shimmer like frozen sapphires, and its wings scatter light into prismatic shards when it takes flight. But its beauty is a herald of death. It wraps itself in veils of refracted light, causing blades and arrows to pass through empty air while the creature watches from inches away. Hunters report finding enormous lumps of ice with great bites taken from them, as though the creature feeds upon the cold itself.',
                loot       = {
                    { id = 1108, rate = 'Rare' },
                    { id = 4105, rate = 'Uncommon' },
                    { id = 3298, rate = 'Common' },
                    { id = 2015, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                    { id = 21384, rate = 'Very Common' },
                    { id = 28640, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 28640, augs = { 'MP+15', 'Pet: DEF+5', 'Fast Cast+2%' } },
                    { id = 21384, augs = { 'MP+15', 'Enmity-5', 'INT+3' } },
                },
            },
            {
                name       = 'Searing Eldrake',
                zone       = 'Ifrit\'s Cauldron',
                lv         = 66,
                difficulty = 3,
                description = 'Deep within the smoldering bowels of Ifrit\'s Cauldron, where rivers of magma carve the stone, there dwells a dragon older than memory. A Bastokan mining expedition ventured too deep in search of rare ores. Of thirty miners, two returned. They spoke of a shadow in the flames, a beast whose body radiated such heat that their armor blistered on sight. Its breath sears the spirit, leaving survivors weakened by lingering embers that smolder beneath the skin long after the battle is over. Its gaze is said to petrify not with magic, but with primal terror, so ancient and hateful that the body simply refuses to move.',
                loot       = {
                    { id = 1108, rate = 'Rare' },
                    { id = 3297, rate = 'Common' },
                    { id = 2015, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                    { id = 21385, rate = 'Very Common' },
                    { id = 28514, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 28514, augs = { 'HP+15', 'MP+15', 'Conserve MP+2' } },
                    { id = 21385, augs = { 'HP+15', 'Accuracy+5', 'Attack+2' } },
                },
            },
            {
                name       = 'Venomous Drake',
                zone       = 'Crawler\'s Nest',
                lv         = 66,
                difficulty = 3,
                loot       = {
                    { id = 4566, rate = 'Uncommon' },
                    { id = 3302, rate = 'Common' },
                    { id = 2015, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 39100, augs = { 'Accuracy+5', 'Pet: Store TP+5', 'Automaton Ranged Skill+2' } },
                    { id = 39101, augs = { 'MP+15', 'Water Mag.Acc.+5', 'Enfeebling Magic Duration +2' } },
                },
            },
        },
    },
    {
        section = 'Tier 2 - Wyrms',
        dragons = {
            {
                name       = 'Arfarvegr',
                zone       = 'Pashhow Marshlands',
                lv         = 97,
                difficulty = 4,
                description = 'In the stagnant heart of Pashhow Marshlands, where mist clings to the water, Arfarvegr has ruled unchallenged since before the founding of the three nations. It is a wyrm of water and shadow, and the swamp bends to its will. When it hunts, the marshes rise: brackish floods swallowing paths, crabs and beasts stirring from the muck as if called to war. Its most terrifying gift is its ability to drink the life from its wounds. Those who cut deep find the wyrm only grows stronger, its blood-red eyes brightening with every blow it absorbs. It is lightning that the beast fears most: the crack of thunder that disrupts the endless flow of water through its veins.',
                loot       = {
                    { id = 1342, rate = 'Rare' },
                    { id = 1328, rate = 'Rare' },
                    { id = 1331, rate = 'Rare' },
                    { id = 1315, rate = 'Rare' },
                    { id = 9515, rate = 'Rare' },
                    { id = 21381, rate = 'Rare' },
                    { id = 20740, rate = 'Rare' },
                    { id = 1311, rate = 'Rare' },
                    { id = 1816, rate = 'Rare' },
                    { id = 1703, rate = 'Uncommon' },
                    { id = 27738, rate = 'Common' },
                    { id = 28459, rate = 'Common' },
                    { id = 28062, rate = 'Common' },
                    { id = 9454, rate = 'Common' },
                    { id = 4272, rate = 'Common' },
                    { id = 4486, rate = 'Common' },
                    { id = 1712, rate = 'Common' },
                    { id = 9447, rate = 'Very Common' },
                    { id = 9453, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                    { id = 1110, rate = 'Very Common' },
                    { id = 1313, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 27738, augs = { 'Attack+5', 'Accuracy+5', 'Dbl.Atk.+2%' } },
                    { id = 28459, augs = { 'DEX+5', 'Marksmanship Skill+5', 'AGI+2' } },
                    { id = 28062, augs = { 'INT+5', 'Enmity-5', 'Magic crit. hit rate+2%' } },
                    { id = 20740, augs = { 'VIT+5', 'Parrying Rate +5%', 'Magic dmg. taken -2%' } },
                    { id = 21381, augs = { 'Pet: Accuracy+5 Rng.Acc+1', 'Pet: Attack+5 Rng.Atk.+1', 'Pet: Damage taken -3%' } },
                },
            },
            {
                name       = 'Midgardsormr',
                zone       = 'Meriphataud Mountains',
                lv         = 97,
                difficulty = 4,
                description = 'The oldest texts call it the Serpent Beneath, the one who sleeps in the roots of the Meriphataud mountains. When Midgardsormr walks, the mountains tremble. When it takes to the sky, boulders rain from its hide like an avalanche given wings. Its scales are harder than mythril, fused with the very bedrock it slumbers upon. Wherever it treads, the smaller drakes of the mountain descend in waves, drawn to their sovereign\'s fury. When the World Serpent beats its wings, a shell of living rock encases its body. Only the howling wind can find the cracks in its earthen armor.',
                loot       = {
                    { id = 1333, rate = 'Rare' },
                    { id = 1326, rate = 'Rare' },
                    { id = 1322, rate = 'Rare' },
                    { id = 1335, rate = 'Rare' },
                    { id = 9515, rate = 'Rare' },
                    { id = 28388, rate = 'Rare' },
                    { id = 20554, rate = 'Rare' },
                    { id = 1311, rate = 'Rare' },
                    { id = 1816, rate = 'Rare' },
                    { id = 1703, rate = 'Uncommon' },
                    { id = 28577, rate = 'Common' },
                    { id = 27767, rate = 'Common' },
                    { id = 28201, rate = 'Common' },
                    { id = 9454, rate = 'Common' },
                    { id = 4272, rate = 'Common' },
                    { id = 4486, rate = 'Common' },
                    { id = 1712, rate = 'Common' },
                    { id = 9447, rate = 'Very Common' },
                    { id = 9453, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                    { id = 1110, rate = 'Very Common' },
                    { id = 1313, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 28577, augs = { 'VIT+5', 'Accuracy+5', 'Damage Taken -2%' } },
                    { id = 28201, augs = { 'DEX+5', 'Attack+5', 'Dual Wield+2' } },
                    { id = 27767, augs = { 'MND+5', 'Enmity-5', 'Fast Cast+2%' } },
                    { id = 20554, augs = { 'Attack+5', 'Enmity+5', 'Counter+2' } },
                    { id = 28388, augs = { 'Attack+10', 'Mag.Acc.+10', 'Dual Wield+3' } },
                },
            },
            {
                name       = 'Skrudningr',
                zone       = 'Jugner Forest',
                lv         = 97,
                difficulty = 4,
                description = 'Jugner Forest has always been a place of ancient power, and Skrudningr is its guardian and its curse. This wyrm crackles with barely contained lightning, and the trees nearest its lair is blackened and split from the perpetual discharge of its body. It does not breathe fire like the drakes of legend. It exhales raw thunder, bolts of destruction that arc between targets and scorch the earth. It commands the lesser wyverns of the forest, who swoop from the canopy while their master builds charge for another devastating assault. Spikes of living lightning crackle across its hide, punishing any who dare strike it with steel. The old hunters knew that earth grounds lightning.',
                loot       = {
                    { id = 9515, rate = 'Rare' },
                    { id = 28457, rate = 'Rare' },
                    { id = 21915, rate = 'Rare' },
                    { id = 1311, rate = 'Rare' },
                    { id = 1816, rate = 'Rare' },
                    { id = 1703, rate = 'Uncommon' },
                    { id = 27779, rate = 'Common' },
                    { id = 28384, rate = 'Common' },
                    { id = 28458, rate = 'Common' },
                    { id = 9454, rate = 'Common' },
                    { id = 4272, rate = 'Common' },
                    { id = 4486, rate = 'Common' },
                    { id = 1712, rate = 'Common' },
                    { id = 1321, rate = 'Very Common' },
                    { id = 1334, rate = 'Very Common' },
                    { id = 1317, rate = 'Very Common' },
                    { id = 1340, rate = 'Very Common' },
                    { id = 9447, rate = 'Very Common' },
                    { id = 9453, rate = 'Very Common' },
                    { id = 1133, rate = 'Very Common' },
                    { id = 1110, rate = 'Very Common' },
                    { id = 1313, rate = 'Very Common' },
                },
                equipment  = {
                    { id = 27779, augs = { 'Attack+5', 'Accuracy+5', 'Dual Wield+2' } },
                    { id = 28384, augs = { 'STR+5', 'Attack+5', 'Snapshot+2' } },
                    { id = 28458, augs = { 'MP+15', 'MND+5', 'Blood Pact ability delay -2' } },
                    { id = 21915, augs = { 'DMG:+5', 'DEX+5', 'Haste+2%' } },
                    { id = 28457, augs = { 'Attack+5', 'Pet: Attack+5 Rng.Atk.+1', 'Pet: Haste+3' } },
                },
            },
        },
    },
    {
        section = 'Tier 3 - Elder Wyrms',
        dragons = {
            {
                name       = 'Brjota',
                zone       = 'Bibiki Bay',
                lv         = 99,
                difficulty = 5,
                description = 'There is a reason the fishermen of Bibiki Bay do not sail after dark. Beneath the moonlit waters, where the sea shelf drops into fathomless blue, something vast and terrible makes its home. Brjota is a wyrm of wind, the mightiest of its kind. The gales that surround it silence voice and breath alike. It is attended by Galeweavers: air elementals of tremendous power that are drawn to Brjota as moths to flame. While these servants persist, the wyrm is wreathed in an aura that enhances its strikes, mends its wounds, and feeds its fury. When its wings unfurl, Brjota enters a state of frenzied destruction. During these rampages, not even the ancient disruption techniques can reach it. Only ice, the still and patient opposite of the raging wind, can penetrate Brjota\'s defenses.',
                loot       = {
                    { id = 3545, rate = 'Rare' },
                    { id = 20632, rate = 'Rare' },
                    { id = 20936, rate = 'Rare' },
                    { id = 1311, rate = 'Rare' },
                    { id = 1816, rate = 'Rare' },
                    { id = 1703, rate = 'Uncommon' },
                    { id = 5965, rate = 'Common' },
                    { id = 28305, rate = 'Common' },
                    { id = 28050, rate = 'Common' },
                    { id = 27781, rate = 'Common' },
                    { id = 4272, rate = 'Common' },
                    { id = 4486, rate = 'Common' },
                    { id = 1712, rate = 'Common' },
                    { id = 1320, rate = 'Very Common' },
                    { id = 1325, rate = 'Very Common' },
                    { id = 2430, rate = 'Very Common' },
                    { id = 2435, rate = 'Very Common' },
                    { id = 9447, rate = 'Very Common' },
                    { id = 9453, rate = 'Very Common' },
                    { id = 1110, rate = 'Very Common' },
                    { id = 1313, rate = 'Very Common' },
                    { id = 9454, rate = 'Guaranteed' },
                },
                equipment  = {
                    { id = 28305, augs = { 'Attack+5', 'Accuracy+5', 'Store TP+2' } },
                    { id = 28050, augs = { 'DEX+5', 'Attack+5', 'Dbl.Atk.+2%' } },
                    { id = 27781, augs = { 'AGI+5', 'Accuracy+5', 'Store TP+2' } },
                    { id = 20936, augs = { 'Accuracy+5', 'Zanshin+5', 'Triple Atk.+2%' } },
                    { id = 20632, augs = { 'STR+5', 'Attack+8 Rng.Atk.+1', 'Store TP+3' } },
                },
            },
        },
    },
};


local diff = require('utils/difficulty');

local selected = nil;

local function renderBreadcrumb()
    imgui.PushStyleColor(ImGuiCol_Button, { 0, 0, 0, 0 });
    imgui.PushStyleColor(ImGuiCol_ButtonHovered, { 0.3, 0.2, 0.4, 0.3 });
    imgui.PushStyleColor(ImGuiCol_ButtonActive, { 0.3, 0.2, 0.4, 0.5 });
    if imgui.SmallButton('Dragonslaying##bc') then
        selected = nil;
    end
    imgui.PopStyleColor(3);
    imgui.SameLine(0, 4);
    ui.dim('>');
    imgui.SameLine(0, 4);
    imgui.TextColored(ui.color('white'), selected.name);
    imgui.Separator();
    imgui.Spacing();
end

local function renderEquipItem(entry, idx)
    if items == nil or entry == nil or entry.id == nil then return; end
    local itemId = entry.id;
    local hasAugs = entry.augs and #entry.augs > 0;

    local res = items.getRes(itemId);
    local itemName = items.getName(itemId);
    local desc = '';
    if res and res.Description and res.Description[1] and res.Description[1] ~= '' then
        desc = res.Description[1];
    end

    local jobStr = '';
    local lvlStr = '';
    if res then
        local jobs = items.getJobList(res.Jobs);
        if jobs then jobStr = jobs; end
        if res.Level and res.Level > 0 then lvlStr = string.format('Lv.%d ', res.Level); end
    end
    local hasInfo = (jobStr ~= '' or lvlStr ~= '');

    -- Record start position
    local startY = imgui.GetCursorPosY();

    -- Icon + name
    imgui.SetCursorPosX(14);
    if items.renderIcon(itemId, 24) then
        imgui.SameLine(0, 6);
    else
        imgui.SameLine(38);
    end
    imgui.TextColored(ui.color('white'), itemName);

    -- Hover for tooltip (on the name — shows augments)
    if imgui.IsItemHovered() then items.renderTooltip(itemId, entry.augs); end

    imgui.Indent(14);

    -- Description with element dots
    if desc ~= '' then
        imgui.PushTextWrapPos(0);
        items.renderDescription(desc);
        imgui.PopTextWrapPos();
    end

    -- Jobs + Level
    if hasInfo then
        imgui.TextColored({ 0.55, 0.75, 0.55, 1.0 }, lvlStr .. jobStr);
    end

    imgui.Unindent(14);

    -- Draw background + accent bar retroactively
    local endY = imgui.GetCursorPosY();
    local dl = imgui.GetWindowDrawList();
    local wx, wy = imgui.GetWindowPos();
    local ww = imgui.GetWindowWidth();
    local scrollY = imgui.GetScrollY();
    local topY = wy + startY - scrollY;
    local botY = wy + endY - scrollY;

    local base = ui.color('childBg');
    local bgColor = (idx % 2 == 0)
        and imgui.GetColorU32({ base[1] + 0.06, base[2] + 0.05, base[3] + 0.08, 0.45 })
        or  imgui.GetColorU32({ base[1] + 0.02, base[2] + 0.02, base[3] + 0.03, 0.25 });
    dl:AddRectFilled({ wx, topY }, { wx + ww, botY }, bgColor);
    dl:AddRectFilled({ wx, topY }, { wx + 3, botY }, imgui.GetColorU32(ui.color('accent')));

    -- Invisible selectable over the whole row for tooltip
    imgui.SetCursorPosY(startY);
    imgui.Selectable(string.format('##eqhover_%d_%d', itemId, idx), false,
        ImGuiSelectableFlags_AllowItemOverlap, { 0, endY - startY });
    if imgui.IsItemHovered() then items.renderTooltip(itemId, entry.augs); end

    imgui.Separator();
    imgui.Spacing();
end

local function renderDetail()
    local d = selected;

    imgui.BeginChild('##ds_detail', { 0, -4 }, false);

    ui.colored(d.name, 'header');
    imgui.Spacing();
    ui.kv('Zone:', d.zone, 'dimmed', 'blue');
    ui.kv('Level:', tostring(d.lv), 'dimmed', 'yellow');
    diff.renderKV(d.difficulty, ui);
    imgui.Spacing();

    -- Description
    if d.description and d.description ~= '' then
        imgui.PushTextWrapPos(0);
        imgui.TextColored(ui.color('desc'), d.description);
        imgui.PopTextWrapPos();
        imgui.Spacing();
    end

    -- Unique equipment
    if d.equipment and #d.equipment > 0 then
        ui.sectionHeader('Unique Equipment', #d.equipment);
        imgui.Spacing();
        for ei, entry in ipairs(d.equipment) do
            renderEquipItem(entry, ei);
        end
        imgui.Spacing();
    end

    -- General loot (exclude equipment IDs)
    if d.loot and #d.loot > 0 then
        -- Build set of equipment IDs to exclude
        local equipIds = {};
        if d.equipment then
            for _, entry in ipairs(d.equipment) do
                equipIds[entry.id] = true;
            end
        end

        local filteredLoot = {};
        for _, lootEntry in ipairs(d.loot) do
            if not equipIds[lootEntry.id] then
                table.insert(filteredLoot, lootEntry);
            end
        end

        if #filteredLoot > 0 then
            ui.sectionHeader('Loot', #filteredLoot);
            imgui.Spacing();

            local RATE_COLORS = {
                ['Guaranteed']  = { 1.00, 1.00, 1.00, 1.0 },
                ['Very Common'] = { 0.55, 0.90, 0.55, 1.0 },
                ['Common']      = { 0.55, 0.85, 1.00, 1.0 },
                ['Uncommon']    = { 1.00, 0.92, 0.60, 1.0 },
                ['Rare']        = { 1.00, 0.65, 0.40, 1.0 },
                ['Very Rare']   = { 1.00, 0.45, 0.45, 1.0 },
                ['Super Rare']  = { 0.75, 0.45, 1.00, 1.0 },
                ['Ultra Rare']  = { 0.75, 0.45, 1.00, 1.0 },
            };

            local lootBase = ui.color('childBg');
            for li, lootEntry in ipairs(filteredLoot) do
                local itemId = lootEntry.id;
                local rate = lootEntry.rate or '';
                local lootId = string.format('##dsloot_g_%d_%d', itemId, li);
                local lootBg = { lootBase[1] + 0.02, lootBase[2] + 0.02, lootBase[3] + 0.04, 0.70 };
                imgui.PushStyleColor(ImGuiCol_ChildBg, lootBg);
                imgui.BeginChild(lootId, { -1, 32 }, false);

                imgui.SetCursorPos({ 6, 4 });
                if not items.renderIcon(itemId, 24) then imgui.Dummy({ 24, 24 }); end
                imgui.SameLine(0, 6);
                imgui.SetCursorPosY(8);
                imgui.TextColored(ui.color('white'), items.getName(itemId));

                -- Rate badge on right
                if rate ~= '' then
                    local dl = imgui.GetWindowDrawList();
                    local wx, wy = imgui.GetWindowPos();
                    local ww = imgui.GetWindowWidth();
                    local rateColor = RATE_COLORS[rate] or ui.color('dimmed');
                    local rateW = imgui.CalcTextSize(rate);
                    local bgAlpha = imgui.GetColorU32({ rateColor[1] * 0.3, rateColor[2] * 0.3, rateColor[3] * 0.3, 0.5 });
                    dl:AddRectFilled(
                        { wx + ww - rateW - 16, wy + 7 },
                        { wx + ww - 4, wy + 23 },
                        bgAlpha, 3.0);
                    dl:AddText(
                        { wx + ww - rateW - 10, wy + 9 },
                        imgui.GetColorU32(rateColor), rate);
                end

                imgui.SetCursorPos({ 0, 0 });
                imgui.Selectable(string.format('##dlsel_g_%d_%d', itemId, li), false,
                    ImGuiSelectableFlags_SpanAllColumns, { 0, 32 });
                if imgui.IsItemHovered() then items.renderTooltip(itemId); end
                imgui.EndChild();
                imgui.PopStyleColor(1);
            end
            imgui.Spacing();
        end
    end

    imgui.EndChild();
end

local function renderList()
    imgui.BeginChild('##ds_scroll', { 0, -4 }, false);

    for _, group in ipairs(content) do
        ui.sectionHeader(group.section, #group.dragons);
        imgui.Spacing();

        for idx, dragon in ipairs(group.dragons) do
            local rowId = string.format('##ds_%s_%d', dragon.name, idx);
            local base = ui.color('childBg');
            local isAlt = (idx % 2 == 0);
            local bgColor = isAlt
                and { base[1], base[2], base[3], 0.35 }
                or  { base[1], base[2], base[3], 0.20 };

            imgui.PushStyleColor(ImGuiCol_ChildBg, bgColor);
            imgui.BeginChild(rowId, { -1, 42 }, false);

            imgui.SetCursorPosY(0);
            local clicked = imgui.Selectable(
                string.format('##dsel_%s_%d', dragon.name, idx),
                false, ImGuiSelectableFlags_SpanAllColumns, { 0, 42 });

            local dl = imgui.GetWindowDrawList();
            local wx, wy = imgui.GetWindowPos();
            local ww = imgui.GetWindowWidth();

            dl:AddText({ wx + 8, wy + 4 },
                imgui.GetColorU32(ui.color('white')), dragon.name);

            local subText = string.format('Lv.%d  %s', dragon.lv, dragon.zone);
            dl:AddText({ wx + 8, wy + 22 },
                imgui.GetColorU32(ui.color('dimmed')), subText);

            local dLabel, dColor = diff.get(dragon.difficulty);
            local stW = imgui.CalcTextSize(dLabel);
            dl:AddText({ wx + ww - stW - 8, wy + 4 },
                imgui.GetColorU32(dColor), dLabel);

            -- Equipment preview icons on right side
            if dragon.equipment and #dragon.equipment > 0 and items then
                local iconX = wx + ww - 8;
                for ei = #dragon.equipment, 1, -1 do
                    iconX = iconX - 22;
                end
                imgui.SetCursorPos({ iconX - wx + 1, 22 });
                for ei, entry in ipairs(dragon.equipment) do
                    if ei > 1 then imgui.SameLine(0, 2); end
                    if items.renderIcon(entry.id, 18) then
                        if imgui.IsItemHovered() then items.renderTooltip(entry.id); end
                    end
                end
            end

            imgui.EndChild();
            imgui.PopStyleColor(1);

            if clicked then selected = dragon; end
        end

        imgui.Spacing();
    end

    imgui.EndChild();
end

return {
    name        = 'Dragonslaying',
    icon        = 892,    -- Wyrm Skull
    author      = 'Loxley',
    version     = '1.0',
    description = 'Dragon fight content browser',

    init = function(renderIcon, getItemRes, uiMod, renderTooltip)
        ui = uiMod;
        items = {
            renderIcon    = renderIcon,
            getRes        = getItemRes,
            getName       = function(id)
                local res = getItemRes(id);
                return (res and res.Name and res.Name[1]) or tostring(id);
            end,
            getJobList    = function(jobs)
                if jobs == nil or jobs == 0 then return nil; end
                local JOB_ABBR = {
                    'WAR','MNK','WHM','BLM','RDM','THF','PLD','DRK','BST','BRD',
                    'RNG','SAM','NIN','DRG','SMN','BLU','COR','PUP','DNC','SCH',
                    'GEO','RUN',
                };
                if jobs == 0x3FFFFF or jobs == 0x7FFFFF then return 'All Jobs'; end
                local list = {};
                for i = 1, 22 do
                    if bit.band(jobs, bit.lshift(1, i - 1)) ~= 0 then
                        table.insert(list, JOB_ABBR[i]);
                    end
                end
                return #list > 0 and table.concat(list, '/') or nil;
            end,
            renderDescription = function(desc)
                if desc and desc ~= '' then
                    imgui.TextColored(ui.color('dimmed'), desc);
                end
            end,
            renderTooltip = function(id, augs)
                if renderTooltip then
                    local res = getItemRes(id);
                    local name = (res and res.Name and res.Name[1]) or tostring(id);
                    renderTooltip({ id = id, name = name, qty = 0 });
                end
            end,
        };

        -- Register as a sub-tab in the Quest window
        local ok, questPlugin = pcall(require, 'core/quest');
        if ok and questPlugin and questPlugin.registerSubTab then
            questPlugin.registerSubTab('Dragons', function()
                if selected then renderBreadcrumb(); renderDetail(); else renderList(); end
            end, 20);
        end
    end,
};
