--[[
* lqs/plugins/incursion.lua â Incursion content browser
*
* Auto-generated by scripts/export-incursion.py
* Do not edit manually â re-run the script to update.
]]--

local imgui = require('imgui');
local diff  = require('utils/difficulty');

local ui    = nil;
local items = nil;

local RATE_COLORS = {
    ['Guaranteed']  = { 1.00, 1.00, 1.00, 1.0 },
    ['Very Common'] = { 0.55, 0.90, 0.55, 1.0 },
    ['Common']      = { 0.55, 0.85, 1.00, 1.0 },
    ['Uncommon']    = { 1.00, 0.92, 0.60, 1.0 },
    ['Rare']        = { 1.00, 0.65, 0.40, 1.0 },
    ['Very Rare']   = { 1.00, 0.45, 0.45, 1.0 },
};

local content = {
    {
        section    = 'Allied Incursion - Beastmen Strongholds',
        difficulty = 1,
        instances  = {
            {
                name       = 'Fort Ghelsba',
                difficulty = 1,
                exp        = 2500,
                gil        = 15000,
                currency   = 3951,
                extra      = 28343,
                phases = {
                    {
                        cap  = 8,
                        mobs = { { 'Orcish Grappler', 3 }, { 'Orcish Mesmerizer', 3 }, { 'Orcish Fodder', 3 } },
                        boss = { name = 'Orcish Martial', lv = 11,
                            loot = { { id = 16535, rate = 'Very Common' } },
                        },
                    },
                    {
                        cap  = 10,
                        mobs = { { 'Orcish Grappler', 3 }, { 'Orcish Mesmerizer', 3 }, { 'Orcish Fodder', 3 } },
                        boss = { name = 'Orcish Axesmith', lv = 15,
                            loot = { { id = 16640, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Orcish Flamethrower', 2 } },
                            boss = { name = 'Orcish Torcher', lv = 13 },
                        },
                    },
                    {
                        cap  = 12,
                        mobs = { { 'Orcish Grunt', 3 }, { 'Orcish Neckchopper', 3 }, { 'Orcish Stonechucker', 3 } },
                        boss = { name = 'Orcish Sieger', lv = 19,
                            loot = { { id = 17152, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Sentry Lizard', 5 } },
                            boss = { name = 'Sentinel Lizard', lv = 18 },
                        },
                    },
                    {
                        cap  = 16,
                        mobs = { { 'Orcish Grunt', 3 }, { 'Orcish Neckchopper', 3 }, { 'Orcish Stonechucker', 3 } },
                        boss = { name = 'Orcish Ironlord', lv = 24,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Sentry Lizard', 5 } },
                            boss = { name = 'Bronze Bat', lv = 22 },
                        },
                    },
                },
                case_loot = {
                    { id = 28167, rate = 'Rare' },
                    { id = 28343, rate = 'Rare' },
                    { id = 20844, rate = 'Rare' },
                    { id = 13081, rate = 'Uncommon' },
                },
            },
            {
                name       = 'Giddeus',
                difficulty = 1,
                exp        = 2500,
                gil        = 15000,
                currency   = 3953,
                extra      = 27780,
                phases = {
                    {
                        cap  = 8,
                        mobs = { { 'Yagudo Initiate', 3 }, { 'Yagudo Scribe', 3 }, { 'Yagudo Acolyte', 3 } },
                        boss = { name = 'Yagudo Scout', lv = 11,
                            loot = { { id = 16896, rate = 'Very Common' } },
                        },
                    },
                    {
                        cap  = 10,
                        mobs = { { 'Yagudo Persecutor', 3 }, { 'Yagudo Piper', 3 }, { 'Yagudo Mendicant', 3 } },
                        boss = { name = 'Yagudo Sparrer', lv = 15,
                            loot = { { id = 16385, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Giddeus Pugil', 5 } },
                            boss = { name = 'Venomous Bee', lv = 13 },
                        },
                    },
                    {
                        cap  = 12,
                        mobs = { { 'Yagudo Persecutor', 3 }, { 'Yagudo Piper', 3 }, { 'Yagudo Mendicant', 3 } },
                        boss = { name = 'Yagudo Conjurer', lv = 19,
                            loot = { { id = 4422, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Earth Eater', 5 } },
                            boss = { name = 'Ironscale Pugil', lv = 18 },
                        },
                    },
                    {
                        cap  = 16,
                        mobs = { { 'Yagudo Votary', 3 }, { 'Yagudo Priest', 3 }, { 'Yagudo Theologist', 3 } },
                        boss = { name = 'Yagudo Seer', lv = 24,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Digger Wasp', 5 } },
                            boss = { name = 'Dust Eater', lv = 22 },
                        },
                    },
                },
                case_loot = {
                    { id = 28028, rate = 'Rare' },
                    { id = 27780, rate = 'Rare' },
                    { id = 28610, rate = 'Rare' },
                    { id = 13204, rate = 'Uncommon' },
                },
            },
            {
                name       = 'Palborough Mines',
                difficulty = 1,
                exp        = 2500,
                gil        = 15000,
                currency   = 3952,
                extra      = 20597,
                phases = {
                    {
                        cap  = 8,
                        mobs = { { 'Young Quadav', 3 }, { 'Amber Quadav', 3 }, { 'Amethyst Quadav', 3 } },
                        boss = { name = 'Granite Quadav', lv = 11,
                            loot = { { id = 17024, rate = 'Very Common' } },
                        },
                    },
                    {
                        cap  = 10,
                        mobs = { { 'Greater Quadav', 3 }, { 'Veteran Quadav', 3 }, { 'Onyx Quadav', 3 } },
                        boss = { name = 'Quartz Quadav', lv = 15,
                            loot = { { id = 16768, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Pit Hare', 5 } },
                            boss = { name = 'Death Hare', lv = 13 },
                        },
                    },
                    {
                        cap  = 12,
                        mobs = { { 'Greater Quadav', 3 }, { 'Veteran Quadav', 3 }, { 'Onyx Quadav', 3 } },
                        boss = { name = 'Obsidian Quadav', lv = 19,
                            loot = { { id = 4299, rate = 'Very Common' } },
                        },
                        bonus = {
                            mobs = { { 'Copper Beetle', 5 } },
                            boss = { name = 'Brass Beetle', lv = 18 },
                        },
                    },
                    {
                        cap  = 16,
                        mobs = { { 'Old Quadav', 3 }, { 'Copper Quadav', 3 }, { 'Brass Quadav', 3 } },
                        boss = { name = 'Marble Quadav', lv = 24,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Scimitar Scorpion', 2 } },
                            boss = { name = 'Mine Stinger', lv = 22 },
                        },
                    },
                },
                case_loot = {
                    { id = 27739, rate = 'Rare' },
                    { id = 20597, rate = 'Rare' },
                    { id = 27737, rate = 'Rare' },
                    { id = 13465, rate = 'Uncommon' },
                },
            },
        },
    },
    {
        section    = 'Allied Incursion - Cave Expeditions',
        difficulty = 2,
        instances  = {
            {
                name       = 'Dangruf Wadi',
                difficulty = 2,
                exp        = 1500,
                gil        = 20000,
                phases = {
                    {
                        cap  = 15,
                        mobs = { { 'Couloir Leech', 3 } },
                        boss = { name = 'Bloated Leech', lv = 19,
                            loot = {},
                        },
                    },
                    {
                        cap  = 18,
                        mobs = { { 'Couloir Leech', 3 }, { 'Prim Pika', 3 } },
                        boss = { name = 'Burrowing Pika', lv = 22,
                            loot = {},
                        },
                    },
                    {
                        cap  = 20,
                        mobs = { { 'Goblin Bladesmith', 3 }, { 'Goblin Healer', 3 }, { 'Prim Pika', 3 } },
                        boss = { name = 'Goblin Smelter', lv = 24,
                            loot = {},
                        },
                    },
                    {
                        cap  = 22,
                        mobs = { { 'Goblin Bladesmith', 3 }, { 'Goblin Healer', 3 }, { 'Prim Pika', 3 }, { 'Trimmer', 3 } },
                        boss = { name = 'Scalehide', lv = 27,
                            loot = {},
                        },
                    },
                    {
                        cap  = 24,
                        mobs = { { 'Goblin Healer', 3 }, { 'Trimmer', 3 } },
                        boss = { name = 'Magma Crab', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 26,
                        mobs = { { 'Trimmer', 3 }, { 'Natty Gibbon', 3 }, { 'Goblin Bushwhacker', 3 }, { 'Goblin Brigand', 3 } },
                        boss = { name = 'Savage Gibbon', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 28,
                        mobs = { { 'Natty Gibbon', 3 }, { 'Fume Lizard', 3 }, { 'Goblin Brigand', 3 } },
                        boss = { name = 'Goblin Marauder', lv = 34,
                            loot = {},
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Fume Lizard', 3 } },
                        boss = { name = 'Cinder Newt', lv = 36,
                            loot = {},
                            final = true,
                        },
                    },
                },
                case_loot = {
                    { id = 39045, rate = 'Rare' },
                    { id = 39046, rate = 'Rare' },
                    { id = 39047, rate = 'Rare' },
                    { id = 13203, rate = 'Uncommon' },
                    { id = 3954, rate = 'Uncommon' },
                    { id = 3955, rate = 'Uncommon' },
                    { id = 3956, rate = 'Uncommon' },
                    { id = 3951, rate = 'Common' },
                    { id = 3952, rate = 'Common' },
                    { id = 3953, rate = 'Common' },
                },
            },
            {
                name       = 'Maze of Shakhrami',
                difficulty = 2,
                exp        = 1500,
                gil        = 20000,
                phases = {
                    {
                        cap  = 15,
                        mobs = { { 'Stink Bats', 3 }, { 'Maze Maker', 3 }, { 'Goblin Butcher', 3 }, { 'Goblin Tinkerer', 3 }, { 'Goblin Ambusher', 3 } },
                        boss = { name = 'Scarlet Swarm', lv = 19,
                            loot = {},
                        },
                    },
                    {
                        cap  = 18,
                        mobs = { { 'Combat', 3 }, { 'Carnivorous Crawler', 3 } },
                        boss = { name = 'Jade Crawler', lv = 22,
                            loot = {},
                        },
                    },
                    {
                        cap  = 20,
                        mobs = { { 'Carnivorous Crawler', 3 }, { 'Maze Scorpion', 3 } },
                        boss = { name = 'Shell Reaper', lv = 24,
                            loot = {},
                        },
                    },
                    {
                        cap  = 22,
                        mobs = { { 'Goblin Mugger', 3 }, { 'Goblin Leecher', 3 }, { 'Goblin Gambler', 3 }, { 'Ancient Bat', 3 }, { 'Labyrinth Scorpion', 3 } },
                        boss = { name = 'Goblin Pillager', lv = 27,
                            loot = {},
                        },
                    },
                    {
                        cap  = 24,
                        mobs = { { 'Wight', 3 }, { 'Ghoul', 3 }, { 'Carnivorous Crawler', 3 } },
                        boss = { name = 'Marrow Wendigo', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 26,
                        mobs = { { 'Crypterpillar', 3 }, { 'Bleeder Leech', 3 }, { 'Warren Bat', 3 }, { 'Chaser Bats', 3 } },
                        boss = { name = 'Toxic Jelly', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 28,
                        mobs = { { 'Crypterpillar', 3 }, { 'Bleeder Leech', 3 }, { 'Warren Bat', 3 }, { 'Chaser Bats', 3 } },
                        boss = { name = 'Sapphire Leech', lv = 34,
                            loot = {},
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Wight', 3 } },
                        boss = { name = 'Crypt Watcher', lv = 36,
                            loot = {},
                            final = true,
                        },
                    },
                },
                case_loot = {
                    { id = 39042, rate = 'Rare' },
                    { id = 39043, rate = 'Rare' },
                    { id = 39044, rate = 'Rare' },
                    { id = 13441, rate = 'Uncommon' },
                    { id = 3954, rate = 'Uncommon' },
                    { id = 3955, rate = 'Uncommon' },
                    { id = 3956, rate = 'Uncommon' },
                    { id = 3951, rate = 'Common' },
                    { id = 3952, rate = 'Common' },
                    { id = 3953, rate = 'Common' },
                },
            },
            {
                name       = 'Ordelle\'s Caves',
                difficulty = 2,
                exp        = 1500,
                gil        = 20000,
                phases = {
                    {
                        cap  = 15,
                        mobs = { { 'Snipper', 3 }, { 'Stink Bats', 3 }, { 'Blood Bunny', 3 } },
                        boss = { name = 'Crusty Carl', lv = 19,
                            loot = {},
                        },
                    },
                    {
                        cap  = 18,
                        mobs = { { 'Goblin Ambusher', 3 }, { 'Goblin Butcher', 3 }, { 'Goblin Tinkerer', 3 } },
                        boss = { name = 'Goblin Marauder', lv = 22,
                            loot = {},
                        },
                    },
                    {
                        cap  = 20,
                        mobs = { { 'Stalking Sapling', 3 }, { 'Hognosed Bat', 3 }, { 'Fly Agaric', 3 } },
                        boss = { name = 'Frogotten Mold', lv = 24,
                            loot = { { id = 4373, rate = 'Very Common' } },
                        },
                    },
                    {
                        cap  = 22,
                        mobs = { { 'Goblin Leecher', 3 }, { 'Goblin Mugger', 3 }, { 'Goblin Gambler', 3 } },
                        boss = { name = 'Clubsnout Oxlix', lv = 27,
                            loot = { { id = 4425, rate = 'Very Common' } },
                        },
                    },
                    {
                        cap  = 24,
                        mobs = { { 'Dung Beetle', 3 }, { 'Vorpal Bunny', 3 } },
                        boss = { name = 'Bigshell Billy', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 26,
                        mobs = { { 'Poison Leech', 3 }, { 'Jelly', 3 } },
                        boss = { name = 'Jolly Jelly', lv = 30,
                            loot = {},
                        },
                    },
                    {
                        cap  = 28,
                        mobs = { { 'Targe Beetle', 3 } },
                        boss = { name = 'Terrortooth', lv = 34,
                            loot = {},
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Goblin Shaman', 3 }, { 'Goblin Pathfinder', 3 }, { 'Goblin Furrier', 3 }, { 'Goblin Smithy', 3 } },
                        boss = { name = 'Charming Clairy', lv = 36,
                            loot = {},
                            final = true,
                        },
                    },
                },
                case_loot = {
                    { id = 20615, rate = 'Rare' },
                    { id = 22198, rate = 'Rare' },
                    { id = 27516, rate = 'Rare' },
                    { id = 13222, rate = 'Uncommon' },
                    { id = 3954, rate = 'Uncommon' },
                    { id = 3955, rate = 'Uncommon' },
                    { id = 3956, rate = 'Uncommon' },
                    { id = 3951, rate = 'Common' },
                    { id = 3952, rate = 'Common' },
                    { id = 3953, rate = 'Common' },
                },
            },
        },
    },
    {
        section    = 'Allied Incursion - Stronghold Assault',
        difficulty = 3,
        instances  = {
            {
                name       = 'Beadeaux',
                difficulty = 3,
                exp        = 5000,
                gil        = 25000,
                currency   = 3952,
                extra      = 11051,
                phases = {
                    {
                        cap  = 20,
                        mobs = { { 'Copper Quadav', 3 }, { 'Brass Quadav', 3 }, { 'Old Quadav', 3 } },
                        boss = { name = 'Flint Quadav', lv = 28,
                            loot = { { id = 12449, rate = 'Common' } },
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Silver Quadav', 3 }, { 'Garnet Quadav', 3 }, { 'Zircon Quadav', 3 }, { 'Bronze Quadav', 3 } },
                        boss = { name = 'Opal Quadav', lv = 38,
                            loot = { { id = 17042, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'Caterpillar', 5 } },
                            boss = { name = 'Earthen Grub', lv = 35 },
                        },
                    },
                    {
                        cap  = 40,
                        mobs = { { 'Iron Quadav', 3 }, { 'Spinel Quadav', 3 }, { 'Emerald Quadav', 3 }, { 'Elder Quadav', 3 } },
                        boss = { name = 'Aged Quadav', lv = 48,
                            loot = { { id = 17088, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'Charging Sheep', 2 } },
                            boss = { name = 'Barraging sheep', lv = 45 },
                        },
                    },
                    {
                        cap  = 50,
                        mobs = { { 'Gold Quadav', 3 }, { 'Mythril Quadav', 3 }, { 'Steel Quadav', 3 }, { 'Topaz Quadav', 3 } },
                        boss = { name = 'Bismuth Quadav', lv = 58,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Broo', 5 } },
                            boss = { name = 'Bru', lv = 56 },
                        },
                    },
                },
                case_loot = {
                    { id = 22119, rate = 'Rare' },
                    { id = 11051, rate = 'Rare' },
                    { id = 10993, rate = 'Rare' },
                    { id = 19105, rate = 'Uncommon' },
                },
            },
            {
                name       = 'Castle Oztroja',
                difficulty = 3,
                exp        = 5000,
                gil        = 25000,
                currency   = 3953,
                extra      = 21905,
                phases = {
                    {
                        cap  = 20,
                        mobs = { { 'Yagudo Votary', 3 }, { 'Yagudo Priest', 3 }, { 'Yagudo Theologist', 3 } },
                        boss = { name = 'Yagudo Bouncer', lv = 28,
                            loot = { { id = 12457, rate = 'Common' } },
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Yagudo Herald', 3 }, { 'Yagudo Interrogator', 3 }, { 'Yagudo Oracle', 3 }, { 'Yagudo Drummer', 3 } },
                        boss = { name = 'Yagudo Diviner', lv = 38,
                            loot = { { id = 4733, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'Meat Maggot', 5 } },
                            boss = { name = 'Herb Crawler', lv = 35 },
                        },
                    },
                    {
                        cap  = 40,
                        mobs = { { 'Yagudo Conquistador', 3 }, { 'Yagudo Lutenist', 3 }, { 'Yagudo Prior', 3 }, { 'Yagudo Zealot', 3 } },
                        boss = { name = 'Yagudo Whistler', lv = 48,
                            loot = { { id = 5008, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'Bulwark Bat', 5 } },
                            boss = { name = 'Bloodfang Bat', lv = 35 },
                        },
                    },
                    {
                        cap  = 50,
                        mobs = { { 'Yagudo Chanter', 3 }, { 'Yagudo Abbot', 3 }, { 'Yagudo Sentinel', 3 }, { 'Yagudo Inquisitor', 3 } },
                        boss = { name = 'Yagudo Keeper', lv = 58,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Yagudo Parasite', 3 } },
                            boss = { name = 'Yagudo Sucker', lv = 56 },
                        },
                    },
                },
                case_loot = {
                    { id = 10787, rate = 'Rare' },
                    { id = 21905, rate = 'Rare' },
                    { id = 10893, rate = 'Rare' },
                    { id = 17162, rate = 'Uncommon' },
                },
            },
            {
                name       = 'Davoi',
                difficulty = 3,
                exp        = 5000,
                gil        = 25000,
                currency   = 3951,
                extra      = 10992,
                phases = {
                    {
                        cap  = 20,
                        mobs = { { 'Orcish Fighter', 3 }, { 'Orcish Serjeant', 3 }, { 'Orcish Cursemaker', 3 } },
                        boss = { name = 'Orcish Marcher', lv = 28,
                            loot = { { id = 12441, rate = 'Common' } },
                        },
                    },
                    {
                        cap  = 30,
                        mobs = { { 'Orcish Beastrider', 3 }, { 'Orcish Nightraider', 3 }, { 'Orcish Impaler', 3 }, { 'Orcish Brawler', 3 } },
                        boss = { name = 'Orcish Spearman', lv = 38,
                            loot = { { id = 16833, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'War Lizard', 5 } },
                            boss = { name = 'Battle Lizard', lv = 35 },
                        },
                    },
                    {
                        cap  = 40,
                        mobs = { { 'Orcish Footsoldier', 3 }, { 'Orcish Bowshooter', 3 }, { 'Orcish Trooper', 3 }, { 'Orcish Gladiator', 3 } },
                        boss = { name = 'Orcish Savager', lv = 48,
                            loot = { { id = 16641, rate = 'Common' } },
                        },
                        bonus = {
                            mobs = { { 'Morbol', 2 } },
                            boss = { name = 'River Morbol', lv = 45 },
                        },
                    },
                    {
                        cap  = 50,
                        mobs = { { 'Orcish Veteran', 3 }, { 'Orcish Predator', 3 }, { 'Orcish Warchief', 3 }, { 'Orcish Zerker', 3 } },
                        boss = { name = 'Orcish Watcher', lv = 58,
                            loot = {},
                            final = true,
                        },
                        bonus = {
                            mobs = { { 'Geezard', 5 } },
                            boss = { name = 'Orcish Warcat', lv = 56 },
                        },
                    },
                },
                case_loot = {
                    { id = 10467, rate = 'Rare' },
                    { id = 10992, rate = 'Rare' },
                    { id = 10515, rate = 'Rare' },
                    { id = 13089, rate = 'Uncommon' },
                },
            },
        },
    },
};


local selectedInstance = nil;
local selectedPhase   = nil;

------------------------------------------------------------
-- Breadcrumb
------------------------------------------------------------
local function renderBreadcrumb()
    local parts = { 'Incursion' };
    if selectedInstance then table.insert(parts, selectedInstance.name); end
    if selectedPhase then table.insert(parts, string.format('Phase %d', selectedPhase)); end

    imgui.PushStyleColor(ImGuiCol_Button, { 0, 0, 0, 0 });
    imgui.PushStyleColor(ImGuiCol_ButtonHovered, { 0.3, 0.2, 0.4, 0.3 });
    imgui.PushStyleColor(ImGuiCol_ButtonActive, { 0.3, 0.2, 0.4, 0.5 });

    for i, part in ipairs(parts) do
        local isLast = (i == #parts);
        if not isLast then
            if imgui.SmallButton(part .. '##bc_' .. i) then
                if i == 1 then selectedInstance = nil; selectedPhase = nil;
                elseif i == 2 then selectedPhase = nil; end
            end
            imgui.SameLine(0, 4); ui.dim('>'); imgui.SameLine(0, 4);
        else
            imgui.TextColored(ui.color('white'), part);
        end
    end

    imgui.PopStyleColor(3);
    imgui.Separator();
    imgui.Spacing();
end

------------------------------------------------------------
-- Loot row with rate badge
------------------------------------------------------------
local function renderLootRow(lootEntry, idx)
    if items == nil or lootEntry == nil or lootEntry.id == nil or lootEntry.id == 0 then return; end
    local itemId = lootEntry.id;
    local rate = lootEntry.rate or '';

    local base = ui.color('childBg');
    local rowId = string.format('##incloot_%d_%d', itemId, idx);
    local lootBg = { base[1] + 0.02, base[2] + 0.02, base[3] + 0.04, 0.70 };

    imgui.PushStyleColor(ImGuiCol_ChildBg, lootBg);
    imgui.BeginChild(rowId, { -1, 32 }, false);

    imgui.SetCursorPos({ 6, 4 });
    if not items.renderIcon(itemId, 24) then imgui.Dummy({ 24, 24 }); end
    imgui.SameLine(0, 6);
    imgui.SetCursorPosY(8);
    imgui.TextColored(ui.color('white'), items.getName(itemId));

    if rate ~= '' then
        local dl = imgui.GetWindowDrawList();
        local wx, wy = imgui.GetWindowPos();
        local ww = imgui.GetWindowWidth();
        local rateColor = RATE_COLORS[rate] or ui.color('dimmed');
        local rateW = imgui.CalcTextSize(rate);
        local bgAlpha = imgui.GetColorU32({ rateColor[1] * 0.3, rateColor[2] * 0.3, rateColor[3] * 0.3, 0.5 });
        dl:AddRectFilled({ wx + ww - rateW - 16, wy + 7 }, { wx + ww - 4, wy + 23 }, bgAlpha, 3.0);
        dl:AddText({ wx + ww - rateW - 10, wy + 9 }, imgui.GetColorU32(rateColor), rate);
    end

    imgui.SetCursorPos({ 0, 0 });
    imgui.Selectable(string.format('##inclsel_%d_%d', itemId, idx), false,
        ImGuiSelectableFlags_SpanAllColumns, { 0, 32 });
    if imgui.IsItemHovered() then items.renderTooltip(itemId); end

    imgui.EndChild();
    imgui.PopStyleColor(1);
end

------------------------------------------------------------
-- Phase detail (Level 3)
------------------------------------------------------------
local function renderPhaseDetail()
    local phase = selectedInstance.phases[selectedPhase];
    if phase == nil then selectedPhase = nil; return; end

    imgui.BeginChild('##inc_phase_detail', { 0, -4 }, false);

    ui.colored(phase.boss.name, 'header');
    if phase.boss.final then
        imgui.SameLine(0, 8);
        imgui.TextColored(ui.color('accent'), '[BOSS]');
    end
    imgui.Spacing();

    ui.kv('Level:', tostring(phase.boss.lv), 'dimmed', 'yellow');
    ui.kv('Level Cap:', tostring(phase.cap), 'dimmed', 'yellow');

    -- Mobs
    local hasMobs = phase.mobs and #phase.mobs > 0;
    if hasMobs then
        imgui.Spacing();
        local names = {};
        local total = 0;
        for _, mob in ipairs(phase.mobs) do
            table.insert(names, mob[1]);
            total = total + mob[2];
        end
        ui.kv('Defeat:', string.format('%s (%d)', table.concat(names, ', '), total), 'dimmed', 'white');
    end

    -- Boss loot
    if phase.boss.loot and #phase.boss.loot > 0 then
        imgui.Spacing();
        ui.sectionHeader('Boss Loot', #phase.boss.loot);
        imgui.Spacing();
        for li, lootEntry in ipairs(phase.boss.loot) do
            renderLootRow(lootEntry, li);
        end
    end

    -- Bonus
    if phase.bonus then
        imgui.Spacing();
        ui.sectionHeader('Bonus Objective');
        imgui.Spacing();
        if phase.bonus.mobs and #phase.bonus.mobs > 0 then
            local bnames = {};
            local btotal = 0;
            for _, mob in ipairs(phase.bonus.mobs) do
                table.insert(bnames, mob[1]); btotal = btotal + mob[2];
            end
            ui.kv('Defeat:', string.format('%s (%d)', table.concat(bnames, ', '), btotal), 'dimmed', 'green');
        end
        if phase.bonus.boss then
            imgui.Spacing();
            ui.kv('Bonus Boss:', string.format('%s (Lv.%d)', phase.bonus.boss.name, phase.bonus.boss.lv), 'dimmed', 'accent');
        end
    end

    imgui.EndChild();
end

------------------------------------------------------------
-- Instance detail / phase list (Level 2)
------------------------------------------------------------
local function renderInstanceDetail()
    local inst = selectedInstance;

    imgui.BeginChild('##inc_inst_detail', { 0, -4 }, false);

    diff.renderKV(inst.difficulty, ui);
    ui.kv('Rewards:', string.format('%d EXP, %d Gil', inst.exp, inst.gil), 'dimmed', 'yellow');

    -- Currency + extra items
    if inst.currency and items then
        imgui.Spacing();
        ui.dim('Currency:');
        imgui.SameLine(0, 4);
        if items.renderIcon(inst.currency, 16) then imgui.SameLine(0, 4); end
        imgui.TextColored(ui.color('white'), items.getName(inst.currency));
    end

    imgui.Spacing();
    ui.sectionHeader('Phases', #inst.phases);
    imgui.Spacing();

    local base = ui.color('childBg');

    for pi, phase in ipairs(inst.phases) do
        local isFinal = phase.boss and phase.boss.final;
        local hasMobs = phase.mobs and #phase.mobs > 0;
        local hasBonus = phase.bonus ~= nil;
        local hasLoot = phase.boss.loot and #phase.boss.loot > 0;
        local rowHeight = hasMobs and 38 or 24;

        local rowId = string.format('##inc_phase_%d', pi);
        local isAlt = (pi % 2 == 0);
        local bgColor = isAlt
            and { base[1] + 0.02, base[2] + 0.02, base[3] + 0.04, 0.50 }
            or  { base[1], base[2], base[3], 0.30 };

        imgui.PushStyleColor(ImGuiCol_ChildBg, bgColor);
        imgui.BeginChild(rowId, { -1, rowHeight }, false);

        imgui.SetCursorPosY(0);
        local clicked = imgui.Selectable(
            string.format('##incpsel_%d', pi),
            false, ImGuiSelectableFlags_SpanAllColumns, { 0, rowHeight });

        local dl = imgui.GetWindowDrawList();
        local wx, wy = imgui.GetWindowPos();
        local ww = imgui.GetWindowWidth();

        local barColor = isFinal and ui.color('accent') or ui.color('dimmed');
        dl:AddRectFilled({ wx, wy }, { wx + 3, wy + rowHeight }, imgui.GetColorU32(barColor));

        local nameColor = isFinal and ui.color('accent') or ui.color('white');
        local title = string.format('Phase %d  -  %s (Lv.%d)  Cap:%d', pi, phase.boss.name, phase.boss.lv, phase.cap);
        dl:AddText({ wx + 10, wy + 3 }, imgui.GetColorU32(nameColor), title);

        -- Tags
        local rightX = wx + ww - 8;
        if hasBonus then
            local tag = 'BONUS';
            local tagW = imgui.CalcTextSize(tag);
            rightX = rightX - tagW - 12;
            dl:AddRectFilled({ rightX, wy + 2 }, { rightX + tagW + 8, wy + 16 },
                imgui.GetColorU32({ 0.20, 0.40, 0.20, 0.80 }), 3.0);
            dl:AddText({ rightX + 4, wy + 3 }, imgui.GetColorU32({ 0.40, 0.90, 0.40, 1.0 }), tag);
            rightX = rightX - 4;
        end
        if isFinal then
            local tag = 'BOSS';
            local tagW = imgui.CalcTextSize(tag);
            rightX = rightX - tagW - 12;
            dl:AddRectFilled({ rightX, wy + 2 }, { rightX + tagW + 8, wy + 16 },
                imgui.GetColorU32({ 0.50, 0.25, 0.60, 0.80 }), 3.0);
            dl:AddText({ rightX + 4, wy + 3 }, imgui.GetColorU32(ui.color('white')), tag);
        end

        -- Mobs
        if hasMobs then
            local names = {};
            local total = 0;
            for _, mob in ipairs(phase.mobs) do table.insert(names, mob[1]); total = total + mob[2]; end
            dl:AddText({ wx + 24, wy + 20 }, imgui.GetColorU32(ui.color('dimmed')),
                string.format('%s (%d)', table.concat(names, ', '), total));
        end

        imgui.EndChild();
        imgui.PopStyleColor(1);

        -- Loot icons below phase row
        if hasLoot then
            imgui.Indent(24);
            for li, lootEntry in ipairs(phase.boss.loot) do
                if lootEntry.id and lootEntry.id > 0 then
                    if li > 1 then imgui.SameLine(0, 4); end
                    if items and items.renderIcon(lootEntry.id, 20) then
                        if imgui.IsItemHovered() then items.renderTooltip(lootEntry.id); end
                    end
                end
            end
            imgui.Unindent(24);
        end

        if clicked then selectedPhase = pi; end
    end

    -- Case (chest) loot
    if inst.case_loot and #inst.case_loot > 0 then
        imgui.Spacing();
        ui.sectionHeader('Loot', #inst.case_loot);
        imgui.Spacing();
        for li, lootEntry in ipairs(inst.case_loot) do
            renderLootRow(lootEntry, 100 + li);
        end
    end

    imgui.EndChild();
end

------------------------------------------------------------
-- Instance list (Level 1)
------------------------------------------------------------
local function renderList()
    imgui.BeginChild('##inc_scroll', { 0, -4 }, false);

    for _, group in ipairs(content) do
        ui.sectionHeader(group.section, #group.instances);
        imgui.Spacing();

        for idx, inst in ipairs(group.instances) do
            local rowId = string.format('##inc_%s_%d', inst.name, idx);
            local base = ui.color('childBg');
            local isAlt = (idx % 2 == 0);
            local bgColor = isAlt
                and { base[1], base[2], base[3], 0.35 }
                or  { base[1], base[2], base[3], 0.20 };

            imgui.PushStyleColor(ImGuiCol_ChildBg, bgColor);
            imgui.BeginChild(rowId, { -1, 42 }, false);

            imgui.SetCursorPosY(0);
            local clicked = imgui.Selectable(
                string.format('##isel_%s_%d', inst.name, idx),
                false, ImGuiSelectableFlags_SpanAllColumns, { 0, 42 });

            local dl = imgui.GetWindowDrawList();
            local wx, wy = imgui.GetWindowPos();
            local ww = imgui.GetWindowWidth();

            dl:AddText({ wx + 8, wy + 4 }, imgui.GetColorU32(ui.color('white')), inst.name);

            local finalBoss = inst.phases[#inst.phases].boss.name;
            local subText = string.format('%s  (%d phases)', finalBoss, #inst.phases);
            dl:AddText({ wx + 8, wy + 22 }, imgui.GetColorU32(ui.color('dimmed')), subText);

            local dLabel, dColor = diff.get(inst.difficulty);
            local stW = imgui.CalcTextSize(dLabel);
            dl:AddText({ wx + ww - stW - 8, wy + 12 }, imgui.GetColorU32(dColor), dLabel);

            imgui.EndChild();
            imgui.PopStyleColor(1);

            if clicked then
                selectedInstance = inst;
                selectedPhase = nil;
            end
        end

        imgui.Spacing();
    end

    imgui.EndChild();
end

------------------------------------------------------------
-- Plugin definition
------------------------------------------------------------
return {
    name        = 'Incursion',
    icon        = 3679,   -- Beastman Banner
    author      = 'Loxley',
    version     = '1.0',
    description = 'Incursion content browser',

    init = function(renderIcon, getItemRes, uiMod, renderTooltip)
        ui = uiMod;
        items = {
            renderIcon    = renderIcon,
            getName       = function(id)
                local res = getItemRes(id);
                return (res and res.Name and res.Name[1]) or tostring(id);
            end,
            renderTooltip = function(id, qty)
                if renderTooltip then
                    local res = getItemRes(id);
                    local name = (res and res.Name and res.Name[1]) or tostring(id);
                    renderTooltip({ id = id, name = name, qty = qty or 0 });
                end
            end,
        };

        -- Register as a sub-tab in the Quest window
        local ok, questPlugin = pcall(require, 'core/quest');
        if ok and questPlugin and questPlugin.registerSubTab then
            questPlugin.registerSubTab('Incursion', function()
                if selectedInstance then renderBreadcrumb(); end
                if selectedPhase then renderPhaseDetail();
                elseif selectedInstance then renderInstanceDetail();
                else renderList(); end
            end, 10);
        end
    end,
};
